/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Workbook;

import Controller.WorkbookController;
import Model.User;
import View.User.LoginView;
import javax.swing.JOptionPane;

/**
 *
 * @author Nefonfo
 */
public class CreateWorkbook extends javax.swing.JFrame {
    
    private final User user;
    private final WorkbookController controller = new WorkbookController();
    /**
     * Creates new form CreateHomework
     * @param user
     */
    public CreateWorkbook(User user) {
        this.user = user;
        initComponents();
        this.title_label.setText(this.title_label.getText()+ " " + this.user.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_label = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        content_label = new javax.swing.JLabel();
        content_input = new javax.swing.JScrollPane();
        content_inputx = new javax.swing.JTextArea();
        return_button = new javax.swing.JToggleButton();
        save_button = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_label.setText("Nueva libreta para: ");
        title_label.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N

        name_input.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N

        name_label.setText("Nombre de la libreta:");
        name_label.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N

        content_label.setText("Contenido:");
        content_label.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N

        content_inputx.setColumns(20);
        content_inputx.setRows(5);
        content_inputx.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        content_input.setViewportView(content_inputx);

        return_button.setText("Regresar");
        return_button.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        save_button.setText("Guardar");
        save_button.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content_input, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addComponent(title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name_input))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(content_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(return_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content_input, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(return_button)
                    .addComponent(save_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_buttonActionPerformed
        try {
            new MyWorkbooks(this.user).setVisible(true);
        } catch (Exception ex) {
            new LoginView().setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_return_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        String message;
        try {
            
            message = this.controller.create_wb(this.user.getId(),
                    this.name_input.getText(),
                    this.content_inputx.getText());
            
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        
        JOptionPane.showMessageDialog(this, message);
        
        try {
            new MyWorkbooks(user).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            new LoginView().setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_save_buttonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane content_input;
    private javax.swing.JTextArea content_inputx;
    private javax.swing.JLabel content_label;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel name_label;
    private javax.swing.JToggleButton return_button;
    private javax.swing.JToggleButton save_button;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
