/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.User;

import Controller.UserController;
import Model.User;
import View.Homework.MyHomeworks;
import View.Workbook.MyWorkbooks;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nefonfo
 */
public class ProfileView extends javax.swing.JFrame {

    private final UserController controller = new UserController();
    private final User user;
    /**
     * Creates new form ProfileView
     * @param id
     */
    public ProfileView(int id) {
        initComponents();
        this.user = this.controller.get_user_by_id(id);
        this.welcome_label.setText(this.welcome_label.getText() + this.user.name);
        this.name_input.setText(this.user.name);
        this.email_input.setText(this.user.email);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homework_button = new javax.swing.JButton();
        workbook_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        advice_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        cpassword_input = new javax.swing.JPasswordField();
        cpassword_label = new javax.swing.JLabel();
        update_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(55, 65, 81));

        jPanel2.setBackground(new java.awt.Color(17, 24, 39));

        homework_button.setBackground(new java.awt.Color(17, 24, 39));
        homework_button.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        homework_button.setForeground(new java.awt.Color(255, 255, 255));
        homework_button.setText("Tareas");
        homework_button.setBorderPainted(false);
        homework_button.setFocusPainted(false);
        homework_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homework_buttonActionPerformed(evt);
            }
        });

        workbook_button.setBackground(new java.awt.Color(17, 24, 39));
        workbook_button.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        workbook_button.setForeground(new java.awt.Color(255, 255, 255));
        workbook_button.setText("Libretas");
        workbook_button.setBorderPainted(false);
        workbook_button.setFocusPainted(false);
        workbook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workbook_buttonActionPerformed(evt);
            }
        });

        exit_button.setBackground(new java.awt.Color(17, 24, 39));
        exit_button.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        exit_button.setForeground(new java.awt.Color(255, 255, 255));
        exit_button.setText("Salir");
        exit_button.setBorderPainted(false);
        exit_button.setFocusPainted(false);
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(55, 65, 81));

        welcome_label.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        welcome_label.setText("Bienvenido, ");

        name_label.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        name_label.setForeground(new java.awt.Color(255, 255, 255));
        name_label.setLabelFor(name_input);
        name_label.setText("Nombre del Usuario");

        email_label.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        email_label.setForeground(new java.awt.Color(255, 255, 255));
        email_label.setLabelFor(email_input);
        email_label.setText("Correo");

        email_input.setToolTipText("");

        advice_label.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        advice_label.setForeground(new java.awt.Color(255, 255, 255));
        advice_label.setText("* En caso de querer cambiar la contraseña, escriba la nueva");

        password_label.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        password_label.setForeground(new java.awt.Color(255, 255, 255));
        password_label.setLabelFor(password_input);
        password_label.setText("Contraseña");

        cpassword_label.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        cpassword_label.setForeground(new java.awt.Color(255, 255, 255));
        cpassword_label.setLabelFor(cpassword_input);
        cpassword_label.setText("Confirmar Contraseña");

        update_button.setBackground(new java.awt.Color(109, 40, 217));
        update_button.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("Actualizar Información");
        update_button.setFocusPainted(false);
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(password_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cpassword_label)
                                .addGap(129, 129, 129)
                                .addComponent(cpassword_input, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(welcome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(advice_label)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_label))
                .addGap(18, 18, 18)
                .addComponent(advice_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpassword_input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpassword_label))
                .addGap(18, 18, 18)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homework_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(workbook_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(exit_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(homework_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workbook_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        String validation;
        String response;
        
        if(String.valueOf(this.password_input.getPassword()).equals("")){
            validation = this.user.validate(
                    this.name_input.getText(),
                    this.email_input.getText(),
                    "",
                    false);
        } else {
            validation = this.user.validate(
                    this.name_input.getText(),
                    this.email_input.getText(),
                    String.valueOf(this.password_input.getPassword()),
                    true);
        }
        if(validation == null) {
            
            if(!this.name_input.getText().equals(this.user.name)) {
                response = this.controller.update_name(
                        this.user.getId(),
                        this.name_input.getText());
                JOptionPane.showMessageDialog(this, "Nombre de Usuario: " + response);
            }
            
            if(!this.email_input.getText().equals(this.user.email)) {
                response = this.controller.update_email(
                        this.user.getId(),
                        this.email_input.getText());
                JOptionPane.showMessageDialog(this, "Correo: " + response);
            }
            
            if(!String.valueOf(this.password_input.getPassword()).equals("")) {
                response = this.controller.update_password(
                        this.user.getId(),
                        String.valueOf(this.password_input.getPassword()), 
                        String.valueOf(this.cpassword_input.getPassword()));
                JOptionPane.showMessageDialog(this, "Contraseña: " + response);
            }
            
            new ProfileView(this.user.getId()).setVisible(true);
            this.setVisible(false);
            
        } else {
          JOptionPane.showMessageDialog(this, validation);
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        new WelcomeView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void homework_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homework_buttonActionPerformed
        try {
            new MyHomeworks(this.user).setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(ProfileView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homework_buttonActionPerformed

    private void workbook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workbook_buttonActionPerformed
        try {
            new MyWorkbooks(this.user).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ProfileView.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_workbook_buttonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advice_label;
    private javax.swing.JPasswordField cpassword_input;
    private javax.swing.JLabel cpassword_label;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel email_label;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton homework_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel name_label;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton update_button;
    private javax.swing.JLabel welcome_label;
    private javax.swing.JButton workbook_button;
    // End of variables declaration//GEN-END:variables
}
