/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Homework;

import Controller.HomeworkController;
import Model.User;
import View.User.LoginView;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Nefonfo
 */
public class CreateHomework extends javax.swing.JFrame {
    
    private final User user;
    private final HomeworkController controller = new HomeworkController();
    /**
     * Creates new form CreateHomework
     * @param user
     */
    public CreateHomework(User user) {
        this.user = user;
        initComponents();
        this.title_label.setText(this.title_label.getText()+ " " + this.user.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        content_label = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        date_input = new com.github.lgooddatepicker.components.DatePicker();
        content_input = new javax.swing.JScrollPane();
        content_inputx = new javax.swing.JTextArea();
        return_button = new javax.swing.JToggleButton();
        save_button = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 65, 81));

        title_label.setText("Nueva tarea para: ");
        title_label.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));

        name_label.setText("Nombre de la tarea:");
        name_label.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        name_label.setForeground(new java.awt.Color(255, 255, 255));

        date_label.setText("Fecha de Expiración:");
        date_label.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        date_label.setForeground(new java.awt.Color(255, 255, 255));

        content_label.setText("Contenido:");
        content_label.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        content_label.setForeground(new java.awt.Color(255, 255, 255));

        name_input.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N

        content_inputx.setColumns(20);
        content_inputx.setRows(5);
        content_inputx.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        content_input.setViewportView(content_inputx);

        return_button.setText("Regresar");
        return_button.setBackground(new java.awt.Color(109, 40, 217));
        return_button.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        return_button.setForeground(new java.awt.Color(255, 255, 255));
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        save_button.setText("Guardar");
        save_button.setBackground(new java.awt.Color(109, 40, 217));
        save_button.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_label)
                            .addComponent(date_label))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_input, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(date_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(content_input, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(content_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title_label)
                        .addGap(22, 22, 22)
                        .addComponent(name_label)
                        .addGap(18, 18, 18)
                        .addComponent(date_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(content_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_input, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(return_button, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(save_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_buttonActionPerformed
        try {
            new MyHomeworks(this.user).setVisible(true);
        } catch (Exception ex) {
            new LoginView().setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_return_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        String message;
        try {
            
            message = this.controller.create_hw(this.user.getId(),
                    this.name_input.getText(),
                    this.content_inputx.getText(),
                    Date.from(
                            this.date_input.getDate().atStartOfDay(
                                    ZoneId.systemDefault()
                            ).toInstant()
                    )
            );
            
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        
        JOptionPane.showMessageDialog(this, message);
        
        try {
            new MyHomeworks(user).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            new LoginView().setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_save_buttonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane content_input;
    private javax.swing.JTextArea content_inputx;
    private javax.swing.JLabel content_label;
    private com.github.lgooddatepicker.components.DatePicker date_input;
    private javax.swing.JLabel date_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel name_label;
    private javax.swing.JToggleButton return_button;
    private javax.swing.JToggleButton save_button;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
